name: CI

on:
  push: {}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Mise install
      uses: jdx/mise-action@v3
      with:
        github_token: {{ `${{ secrets.GITHUB_TOKEN }}` }}

    - name: Run shellcheck
      run: task test:shellcheck

    - name: Build
      run: task build

    - name: Run Unit Test
      run: task test:unit

    - name: Run E2E Test
      run: task test:e2e

    - name: Run vulnerabilities check
      run: task test:vulnerabilities
